$axure.loadCurrentPage({
  "url":"global_map.html",
  "generationDate":new Date(1394057856962.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d4d78bbecdbb4b3095a66d6eb87395ad",
    "type":"Axure:Page",
    "name":"Global map",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a062a9c13f6a4487902f899066d58470",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":170},
            "size":{
              "width":350,
              "height":270}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "a062a9c13f6a4487902f899066d58470":{
      "scriptId":"u0"}}});